development:
  adapter: redis
  url: <%= AppConfig.redis.url %>
  channel_prefix: mina_test_540_development

test:
  adapter: test

staging:
  adapter: redis
  urll: <%= AppConfig.redis.url %>
  channel_prefix: mina_test_540_staging

production:
  adapter: redis
  url: <%= AppConfig.redis.url %>
  channel_prefix: mina_test_540_production
